// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSlBQd21awN0GiRu1GMwxqRYOdDfT7ea0',
    appId: '1:640391406428:web:771a615434b19666add799',
    messagingSenderId: '640391406428',
    projectId: 'graduation-80cce',
    authDomain: 'graduation-80cce.firebaseapp.com',
    storageBucket: 'graduation-80cce.appspot.com',
    measurementId: 'G-WWF1W5L738',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc3o-bohUa5rDgLqw8DdxFxaJ5SGvDjXY',
    appId: '1:640391406428:android:ce5a73238cdee0adadd799',
    messagingSenderId: '640391406428',
    projectId: 'graduation-80cce',
    storageBucket: 'graduation-80cce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeXXja771wqLB_rr6WPQMj3KynTHMi4so',
    appId: '1:640391406428:ios:9642903af46894fbadd799',
    messagingSenderId: '640391406428',
    projectId: 'graduation-80cce',
    storageBucket: 'graduation-80cce.appspot.com',
    iosBundleId: 'com.example.grad',
  );
}
